version: "3.7"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

    volumes:
      - keycloak:/opt/keycloak/data
    ports:
      - "8080:8080"
    command:
      - "start-dev"

  echo-server:
    image: ealen/echo-server:0.7.0
    restart: always
    ports:
      - "9090:80"

volumes:
  keycloak:
